name: Unit Tests and Version Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

  check-version-increment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version from current branch
        id: current_version
        run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"

      - name: Get version from main branch
        id: main_version
        run: |
          git fetch origin main
          echo "::set-output name=VERSION::$(node -p "require('./package.json').version" -- package.json)"
          working-directory: ${{ github.workspace }}

      - name: Compare versions
        run: |
          if [ "${{ steps.current_version.outputs.VERSION }}" == "${{ steps.main_version.outputs.VERSION }}" ]; then
            echo "Version number must be incremented."
            exit 1
          else
            echo "Version number is incremented."
          fi
